/* Data-derived reading paths. All displayed results use the frozen external cohort. */
(()=>{'use strict';
const D=window.RESPGRAPH_DATA,pts=D.patients,$=s=>document.querySelector(s),pct=n=>(n*100).toFixed(1)+'%',pp=n=>(n>=0?'+':'')+(n*100).toFixed(2)+' pp';
let bridge,step=-1,restore=null;
const links=D.graph.fold_graphs[0].edges.filter(e=>e.a!==e.b);
const pair=[...links].sort((a,b)=>b.similarity-a.similarity||a.a-b.a)[0];
const near=pts.reduce((a,p,i)=>Math.abs(p.p-.5)<Math.abs(pts[a].p-.5)?i:a,0);
const changed=pts.reduce((a,p,i)=>Math.abs(p.p-D.experiments.random.probabilities[i])>Math.abs(pts[a].p-D.experiments.random.probabilities[a])?i:a,0);
const picks=[{key:'pair',title:'最相似的一对',tag:'相似患者 → 检查变化',value:pair.similarity.toFixed(3),unit:'响应相似度',body:pts[pair.a].id+' 与 '+pts[pair.b].id,detail:'看看她们的检查指标，哪些变化相似？',patient:pair.a,compare:pair.b,page:'patient'},
{key:'boundary',title:'接近50%的预测',tag:'预测概率 → 指标贡献',value:pct(pts[near].p),unit:'预测达到 pCR 的概率',body:pts[near].id,detail:'哪些指标把概率推高，哪些又把它拉低？',patient:near,compare:null,page:'patient'},
{key:'structure',title:'改变连线，谁的预测变化最大？',tag:'改变连线 → 预测变化',value:pp(D.experiments.random.probabilities[changed]-pts[changed].p),unit:'随机图 − 相似图',body:pts[changed].id,detail:'模型不变，只改变连线，看看她的概率变了多少。',patient:changed,compare:null,page:'evidence'}];
function cards(){return `<section class="discovery-strip" aria-label="真实数据探索入口"><div class="discovery-lead"><span class="eyebrow">FOLLOW THE EVIDENCE</span><h2>不知道先看谁？试试这三个例子</h2><p>根据这38位患者的真实数据选出，点击即可查看</p></div><div class="discovery-cards">${picks.map((p,i)=>`<button class="discovery-card" data-discovery="${i}"><span class="discovery-tag">0${i+1} / ${p.tag}</span><h3>${p.title}</h3><div class="discovery-value">${p.value}<small>${p.unit}</small></div><strong>${p.body}</strong><p>${p.detail}</p><span class="discovery-arrow" aria-hidden="true">↗</span></button>`).join('')}</div><details class="discovery-method"><summary>案例如何选出</summary><p>分别取实际连边中相似度最高的一对、原始概率距离0.50最近的患者、随机图相对相似图概率绝对变化最大的患者。均由全体数据按固定规则选择，用于探索，不作为代表性样本估计。</p></details></section>`;}
function encoding(){return `<details class="encoding-guide"><summary>读懂这张关系图 <span>点 · 线 · 空间 · 光晕</span></summary><div class="encoding-grid"><div><b>点 / 一位患者</b><p>填色对应0—1原始概率；蓝色更高，橙色更低。验证模式外圈才显示实际结局。</p></div><div><b>线 / 响应相似性</b><p>实线来自阈值关系，虚线为Top-k补充；点击后显示相邻患者及相似度。</p></div><div><b>空间 / 阅读布局</b><p>位置随聚焦和旋转变化。连边决定邻域，屏幕距离不代表模型距离。</p></div><div><b>光晕 / 输出波动</b><p>原队列MC Dropout波动越大，光晕越明显；黄色虚线表示分位范围跨0.50。</p></div></div></details>`;}
function structure(state){const names={similarity:'响应相似图',random:'随机重连图',self:'仅GCN自环'};return `<section class="panel structure-review" id="structure-review"><div class="split-head"><div><div class="eyebrow">SAME MODELS · DIFFERENT GRAPHS</div><h2>不同连线方式，预测表现差多少？</h2></div><span class="badge">同一外部队列 · n = 38</span></div><div class="structure-grid"><div class="auc-comparison">${Object.entries(names).map(([key,title])=>{const m=D.experiments[key].metrics;return `<button class="auc-row" data-review-experiment="${key}" aria-pressed="${state.experiment===key}"><span>${title}</span><div class="auc-track"><i class="auc-fill" style="width:${m.auc*100}%"></i><i class="auc-interval" style="left:${m.auc_ci[0]*100}%;width:${(m.auc_ci[1]-m.auc_ci[0])*100}%"></i><i class="auc-point" style="left:${m.auc*100}%"></i></div><b>${m.auc.toFixed(4)}</b></button>`;}).join('')}<div class="auc-axis"><span>AUC · 0</span><span>0.5</span><span>1</span></div><p class="small muted">圆点为AUC，细线为各设置的95% bootstrap区间。点击一行联动下方证据。</p></div><div class="finding-note"><span class="eyebrow">响应关系的验证结果</span><h3>让患者关系成为预测信息。</h3><p>响应相似图的外部 AUC 为 <strong>${D.metrics.auc.toFixed(4)}</strong>。</p><p>将真实相似关系、随机连线与仅自身连线放在同一尺度上，直观看到不同结构下的预测表现。</p><a href="data.json" download>查看实验数据 ↗</a></div></div></section>`;}
function distribution(state){const ex=D.experiments[state.experiment],values=ex.probabilities,order=pts.map((_,i)=>i).sort((a,b)=>values[a]-values[b]);const W=1100,H=280,L=65,R=25,T=36,B=230,x=i=>L+i/(pts.length-1)*(W-L-R),y=v=>B-v*(B-T);let svg='';
for(const v of [0,.25,.5,.75,1])svg+=`<path d="M${L-8},${y(v)} H${W-R}" stroke="${v===.5?'#bdab72':'#2a455b'}" stroke-dasharray="${v===.5?'6 5':'2 6'}"/><text x="${L-13}" y="${y(v)+5}" text-anchor="end">${v*100}%</text>`;
svg+=`<text x="${W-R}" y="${y(.5)-10}" text-anchor="end">分类阈值 0.50</text>`;
order.forEach((idx,k)=>{const p=pts[idx],v=values[idx],cx=x(k),cy=y(v),color=v>=.5?'#43a5ff':'#f2994a',wrong=(v>=.5)!==!!p.label;svg+=`<g data-ranked-patient="${idx}" tabindex="0" role="button" aria-label="${p.id}，概率${pct(v)}${state.validation?'，实际'+(p.label?'pCR':'non-pCR'):''}"><rect x="${cx-11}" y="${T-12}" width="22" height="${B-T+45}" fill="transparent"/><path d="M${cx},${B} V${cy}" stroke="${color}" stroke-opacity=".36" stroke-width="5"/><circle cx="${cx}" cy="${cy}" r="${idx===state.patient?7:5}" fill="${color}" stroke="${idx===state.patient?'#fff':color}" stroke-width="2"/>${state.validation?(p.label?`<circle cx="${cx}" cy="${B+21}" r="4" fill="#43a5ff"/>`:`<path d="M${cx},${B+16} l5,5 -5,5 -5,-5 Z" fill="#f2994a"/>`)+(wrong?`<path d="M${cx-3},${cy-3} l6,6 m0,-6 l-6,6" stroke="#07111f" stroke-width="1.5"/>`:''):''}<title>${p.id} · ${pct(v)}${state.validation?' · 实际'+(p.label?'pCR':'non-pCR')+(wrong?' · 分类不一致':''):''}</title></g>`;});
const changes=values.map((v,i)=>v-pts[i].p),i=state.patient;return `<section class="panel ranked-section" id="ranked-section"><div class="split-head"><div><div class="eyebrow">EVERY PATIENT COUNTS</div><h2>看看38位患者，哪些预测与实际相符</h2><p>按当前概率从低到高排列；点击任意点，回到她的轨迹与解释。</p></div><button id="ranked-validate" aria-pressed="${state.validation}">${state.validation?'隐藏实际治疗结果':'显示实际治疗结果'}</button></div><div class="ranked-scroll"><svg viewBox="0 0 ${W} ${H}" class="ranked-chart" aria-label="38例患者原始预测排序图">${svg}</svg></div><div class="ranked-caption"><span>${state.validation?'底部圆点：实际pCR · 菱形：实际non-pCR · ×：阈值分类不一致':'实际结局尚未显示，点击“显示实际治疗结果”进行核对。'}</span><span>左：较低概率 → 右：较高概率</span></div><div class="selected-evidence"><strong>${pts[i].id}</strong><span>相似图 ${pct(pts[i].p)}</span><span>当前 ${pct(values[i])}</span><span>变化 ${pp(changes[i])}</span><button data-ranked-patient="${i}">看她的检查和预测依据 →</button></div></section>`;}
const scenes=[
{page:'background',title:'01 / 治疗期间的检查，用来预测什么',text:'三阴性乳腺癌患者在手术前接受治疗；MRI记录变化，手术病理核对是否达到pCR。',target:'.overview-title'},
{page:'story',title:'02 / 一屏看清研究与作品结构',text:'左侧检查变化，中心患者关系，右侧预测解释，下方队列验证。',patient:pair.a,target:'.overview-title'},
{page:'graph',title:'03 / 将患者关系变成可探索的空间',text:'点击患者，镜头与邻域同步聚焦；蓝橙填色表示预测概率，连线显示响应相似性。',patient:pair.a,target:'.space-stage'},
{page:'patient',title:'04 / 完整病例：检查与相似患者',text:'比较EXT-011与EXT-027，观察四项检查变化。相似度来自完整模型输入。',patient:pair.a,compare:pair.b,target:'.patient-layout'},
{page:'patient',title:'05 / 从病例轨迹进入预测解释',text:'EXT-004原始概率48.6%。SHAP分解当前输入相对参考值的贡献。',patient:near,compare:null,explain:'local',target:'.explain-section'},
{page:'patient',title:'06 / 跨患者注意力怎样分配',text:'切换注意力流程与矩阵，查看当前患者对全队列的真实关注权重。',patient:near,explain:'flow',target:'.explain-section'},
{page:'evidence',title:'07 / 核对模型表现与关系价值',text:'外部AUC0.8304。切换相似图、随机连线、仅自身，查看结构对预测的影响；再核对真实结果与概率波动。',experiment:'similarity',validation:true,target:'.structure-review'},
{page:'sandbox',title:'08 / 队列变化后的关系与预测',text:'移除5位患者，展示33人的实际预计算结果。本地版支持增加无标签患者并运行模型。',preset:3,target:'.cohort-camera'},
{page:'boundary',title:'09 / 作品用途与技术贡献',text:'以纵向MRI、患者关系、模型解释和外部验证支持医生的疗效评估研究。',target:'.page-intro'}];
function casewalk(state){const p=pts[state.patient];return `<section class="casewalk"><div class="casewalk-title"><h2>病例演示：从检查到结果核对</h2><span class="badge">当前 ${p.id}</span></div><p>沿着同一条操作路径，看检查变化、相似患者、指标贡献、关注权重和实际结局。</p><div class="casewalk-steps">${['单人检查','双人对照','局部SHAP','注意力机制','核对结局'].map((t,j)=>`<button data-case-step="${j}"><span>0${j+1}</span>${t}</button>`).join('')}</div><div class="casewalk-note"><b>当前结果：</b>预测pCR ${pct(p.p)}${state.validation?' · 实际'+(p.label?'pCR':'non-pCR')+' · 阈值0.50下'+((p.p>=.5)===!!p.label?'预测相符':'预测与结局不一致'):' · 实际结局可在第05步显示'}。</div></section>`;}
function close(){step=-1;$('#tourbar').hidden=true;document.body.classList.remove('presenting');if(restore){bridge.set(restore,restore.page);restore=null;}$('#tour').focus();}
function scene(){const s=scenes[step];bridge.set({patient:s.patient??bridge.state().patient,compare:s.compare??null,focus:true,view:'topology',orbit:false,validation:s.validation??false,experiment:s.experiment??'similarity'},s.page,s.preset);document.body.classList.add('presenting');const bar=$('#tourbar');bar.hidden=false;bar.innerHTML=`<div class="show-progress">${scenes.map((_,i)=>`<i class="${i<=step?'done':''}"></i>`).join('')}</div><div class="show-copy"><span>${step+1} / ${scenes.length} · 演示路径</span><h3>${s.title}</h3><p>${s.text}</p></div><div class="tour-controls"><button id="show-prev" ${step===0?'disabled':''}>← 上一幕</button><button id="show-next" class="primary">${step===scenes.length-1?'结束演示':'下一幕 →'}</button><button id="show-full">全屏</button><button id="show-exit">退出</button></div>`;
$('#show-prev').onclick=()=>{step--;scene();};$('#show-next').onclick=()=>{if(step===scenes.length-1)close();else{step++;scene();}};$('#show-exit').onclick=close;$('#show-full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{bridge.toast('浏览器未允许全屏，可继续演示');}};
requestAnimationFrame(()=>requestAnimationFrame(()=>{if(s.explain)$(`[data-explain-view="${s.explain}"]`)?.click();$(s.target)?.scrollIntoView({block:'start',behavior:'instant'});$('#show-next').focus({preventScroll:true});}));}
function wire(state){document.querySelectorAll('[data-case-step]').forEach(b=>b.onclick=()=>{const j=Number(b.dataset.caseStep),config=j===0?{patient:state.patient,compare:null}:j===1?{patient:pair.a,compare:pair.b}:j===4?{validation:true}:{};bridge.set(config,'patient');requestAnimationFrame(()=>requestAnimationFrame(()=>{if(j===2||j===3)$(`[data-explain-view="${j===2?'local':'flow'}"]`)?.click();$(j===2||j===3?'.explain-section':'.patient-layout')?.scrollIntoView({block:'start',behavior:'instant'});}));});document.querySelectorAll('[data-discovery]').forEach(b=>b.onclick=()=>{const p=picks[Number(b.dataset.discovery)];bridge.set({patient:p.patient,compare:p.compare,focus:true,experiment:p.key==='structure'?'random':'similarity'},p.page);});document.querySelectorAll('[data-review-experiment]').forEach(b=>b.onclick=()=>bridge.set({experiment:b.dataset.reviewExperiment}));document.querySelectorAll('[data-ranked-patient]').forEach(b=>{const choose=()=>bridge.set({patient:Number(b.dataset.rankedPatient),compare:null,focus:true},'patient');b.onclick=choose;b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}};});if($('#ranked-validate'))$('#ranked-validate').onclick=()=>bridge.set({validation:!state.validation});}
function enhance(state){const root=$('#content');if(state.page==='patient')root.querySelector('.toolbar').insertAdjacentHTML('beforebegin',casewalk(state));if(state.page==='graph'){root.insertAdjacentHTML('beforeend',encoding()+cards());const jump=document.createElement('button');jump.textContent='探索案例 ↓';jump.onclick=()=>root.querySelector('.discovery-strip').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});root.querySelector('.toolbar').append(jump);}if(state.page==='evidence'){const toolbar=root.querySelector('.toolbar');toolbar.insertAdjacentHTML('afterend',structure(state)+distribution(state));}wire(state);}
function init(api){bridge=api;$('#tour').textContent='演示作品';$('#tour').onclick=()=>{restore={...bridge.state()};step=0;scene();};document.addEventListener('keydown',e=>{if(step<0||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='Escape'){close();}else if(e.key==='ArrowRight'){e.preventDefault();$('#show-next').click();}else if(e.key==='ArrowLeft'&&step>0){e.preventDefault();$('#show-prev').click();}});document.querySelector('nav').addEventListener('click',()=>{if(step>=0)close();});}
window.RespDiscovery={enhance,init,picks};
})();
