/* Perspective projection of a deterministic 3D force layout. Model edges stay unchanged. */
(()=>{'use strict';
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let canvas,ctx,options,raf=0,previousTime=0,points=[],layout=null,layoutKey=null,displayLayout=null,targetLayout=null,selected=null,hover=-1,pointer=null,drag=null,touches=new Map(),pinch=null;let labels=[],dirty=true,paintedFrames=0,lastPaintMs=0;
const camera={yaw:.4,pitch:-.18,zoom:1,targetZoom:1,pivot:[0,0,0],targetYaw:.4,targetPitch:-.18,targetPivot:[0,0,0]};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function makeLayout(n,edges){const p=Array.from({length:n},(_,i)=>{const y=1-2*(i+.5)/n,r=Math.sqrt(1-y*y),a=i*2.3999632297;return [Math.cos(a)*r,y,Math.sin(a)*r];});const v=p.map(()=>[0,0,0]);
 for(let step=0;step<230;step++){const f=p.map(q=>q.map(x=>-.013*x));for(let i=0;i<n;i++)for(let j=i+1;j<n;j++){const d=p[i].map((x,k)=>x-p[j][k]),r=Math.max(.09,Math.hypot(...d)),force=.018/(r*r);for(let k=0;k<3;k++){f[i][k]+=d[k]/r*force;f[j][k]-=d[k]/r*force;}}
 for(const e of edges){if(e.a===e.b)continue;const d=p[e.b].map((x,k)=>x-p[e.a][k]),r=Math.max(.01,Math.hypot(...d)),force=(r-(.58-.16*e.weight))*.024*Math.max(.25,e.weight);for(let k=0;k<3;k++){f[e.a][k]+=d[k]/r*force;f[e.b][k]-=d[k]/r*force;}}
 for(let i=0;i<n;i++)for(let k=0;k<3;k++){v[i][k]=(v[i][k]+f[i][k])*.72;p[i][k]+=clamp(v[i][k],-.06,.06);}}
 const mean=[0,1,2].map(k=>p.reduce((s,q)=>s+q[k],0)/n),radius=Math.max(...p.map(q=>Math.hypot(...q.map((x,k)=>x-mean[k]))));return p.map(q=>q.map((x,k)=>(x-mean[k])/radius*1.35));}
function focusLayout(index,opt){if(index===null)return layout.map(p=>[...p]);const near=new Map();opt.edges.forEach(e=>{if(e.a!==e.b&&(e.a===index||e.b===index))near.set(e.a===index?e.b:e.a,e.similarity);});const ids=[...near.keys()].sort((a,b)=>near.get(b)-near.get(a));const cy=Math.cos(camera.targetYaw),sy=Math.sin(camera.targetYaw),cp=Math.cos(camera.targetPitch),sp=Math.sin(camera.targetPitch);
return layout.map((p,i)=>{if(i===index)return [...p];let x,y,z;if(near.has(i)){const n=ids.indexOf(i),a=-.65+n/ids.length*Math.PI*2,r=.9+(1-near.get(i))*.25;x=Math.cos(a)*r;y=Math.sin(a)*r;z=Math.sin(n*2.3)*.22;}else{const a=i*2.3999632297,t=1-2*(i+.5)/layout.length,r=Math.sqrt(1-t*t);x=Math.cos(a)*r*1.72;y=t*1.6;z=Math.sin(a)*r*.85+.45;}const yy=y*cp+z*sp,zz=-y*sp+z*cp;return [x*cy-zz*sy+layout[index][0],yy+layout[index][1],x*sy+zz*cy+layout[index][2]];});}
function project(p,w,h){const q=p.map((x,k)=>x-camera.pivot[k]),cy=Math.cos(camera.yaw),sy=Math.sin(camera.yaw),cp=Math.cos(camera.pitch),sp=Math.sin(camera.pitch),x=q[0]*cy+q[2]*sy,z=-q[0]*sy+q[2]*cy,y=q[1]*cp-z*sp,zz=q[1]*sp+z*cp,scale=4.5/Math.max(1.3,4.5+zz),unit=Math.min(w*.25,h*(options.focus?.24:.3))*camera.zoom;return {x:w/2+x*unit*scale,y:h*.46+y*unit*scale,z:zz,scale};}
function line(a,b,color,width=1,dash=[]){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([]);}
function color(p){const a=p<.5?[242,153,74]:[131,147,167],b=p<.5?[131,147,167]:[67,165,255],t=p<.5?p*2:(p-.5)*2;return a.map((v,i)=>Math.round(v+(b[i]-v)*t));}
function textLabel(text,x,y,color='#d9f0ff',align='center'){labels.push({text,x,y,color,align,priority:text===options.patients[options.patient].id||text.includes('%  pCR')?3:text.startsWith('EXT-')||text.startsWith('NEW-')?2:1});}
function paintLabels(w,h){const occupied=[];ctx.font='12px "Microsoft YaHei",sans-serif';labels.sort((a,b)=>b.priority-a.priority);for(const l of labels){const tw=ctx.measureText(l.text).width+12;let box;for(const [dx,dy] of [[0,0],[0,-22],[0,22],[-48,-30],[48,30],[0,-44],[0,44]]){const x=clamp(l.x+dx,tw/2+5,w-tw/2-5),y=clamp(l.y+dy,52,h-45),candidate={x:x-tw/2,y:y-14,w:tw,h:20,cx:x,cy:y};if(!occupied.some(b=>candidate.x<b.x+b.w+4&&candidate.x+tw+4>b.x&&candidate.y<b.y+b.h+3&&candidate.y+20+3>b.y)){box=candidate;break;}}if(!box)continue;occupied.push(box);if(Math.abs(box.cx-l.x)+Math.abs(box.cy-l.y)>8)line({x:l.x,y:l.y+3},{x:box.cx,y:box.cy-5},'rgba(146,186,204,.4)',.7);ctx.fillStyle='rgba(6,12,20,.92)';ctx.fillRect(box.x,box.y,box.w,box.h);ctx.fillStyle=l.color;ctx.textAlign='center';ctx.fillText(l.text,box.cx,box.cy);}}
function backdrop(w,h,time){const g=ctx.createRadialGradient(w*.5,h*.5,10,w*.5,h*.5,w*.7);g.addColorStop(0,'#0b3046');g.addColorStop(.6,'#061b2c');g.addColorStop(1,'#040e19');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
 // Sparse depth field and a perspective reference plane, kept separate from patient data.
 ctx.fillStyle='#56869a';for(let i=0;i<55;i++){const x=((i*137.51)%997)/997*w,y=((i*91.73)%613)/613*h;ctx.globalAlpha=.14+(i%4)*.04;ctx.fillRect(x,y,1,1);}ctx.globalAlpha=1;
 const floorY=1.4;for(let i=-8;i<=8;i++){const a=project([i*.38,floorY,-3],w,h),b=project([i*.38,floorY,3],w,h);line(a,b,'rgba(37,137,166,.10)');line(project([-3,floorY,i*.38],w,h),project([3,floorY,i*.38],w,h),'rgba(37,137,166,.10)');}
 for(const radius of [1.7,2.0]){ctx.beginPath();for(let i=0;i<=100;i++){const a=i/100*Math.PI*2,p=project([Math.cos(a)*radius,floorY,Math.sin(a)*radius],w,h);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);}ctx.strokeStyle='rgba(46,193,210,.24)';ctx.lineWidth=radius===1.7?1.4:.7;ctx.stroke();}
 ctx.strokeStyle='#2d8095';ctx.lineWidth=1;const inset=18,len=20;for(const [x,y,sx,sy] of [[inset,inset,1,1],[w-inset,inset,-1,1],[inset,h-inset,1,-1],[w-inset,h-inset,-1,-1]]){ctx.beginPath();ctx.moveTo(x+len*sx,y);ctx.lineTo(x,y);ctx.lineTo(x,y+len*sy);ctx.stroke();}
 ctx.font='11px monospace';ctx.fillStyle='#689db3';ctx.textAlign='left';ctx.fillText('RESPGRAPH / SPATIAL TOPOLOGY',30,35);ctx.fillText(options.patients.length+' NODES  ·  MRI RESPONSE SIMILARITY',30,h-30);
 ctx.textAlign='right';ctx.fillStyle='#68b3c4';ctx.fillText(options.focus?options.patients[options.patient].id+' / FOCUS':'COHORT / OVERVIEW',w-30,35);
}
function tick(now){if(!canvas||!canvas.isConnected){raf=0;return;}const dt=Math.min((now-previousTime)/1000||.016,.05);previousTime=now;const paintStart=performance.now();const width=canvas.clientWidth,height=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,1.5);if(canvas.width!==Math.round(width*dpr)||canvas.height!==Math.round(height*dpr)){canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);dirty=true;}if(document.hidden){raf=requestAnimationFrame(tick);return;}const cameraMoving=Math.abs(camera.targetYaw-camera.yaw)+Math.abs(camera.targetPitch-camera.pitch)+Math.abs(camera.targetZoom-camera.zoom)+camera.targetPivot.reduce((sum,v,k)=>sum+Math.abs(v-camera.pivot[k]),0)>.0002;const layoutMoving=displayLayout.some((p,i)=>p.some((v,k)=>Math.abs(v-targetLayout[i][k])>.0002));if(!options.orbit&&!dirty&&!cameraMoving&&!layoutMoving){raf=requestAnimationFrame(tick);return;}dirty=false;ctx.setTransform(dpr,0,0,dpr,0,0);const motion=!reduced.matches;labels=[];
 if(options.orbit&&!drag)camera.targetYaw+=dt*.12;
 const ease=motion?1-Math.exp(-dt*5):1;camera.yaw+=(camera.targetYaw-camera.yaw)*ease;camera.pitch+=(camera.targetPitch-camera.pitch)*ease;camera.zoom+=(camera.targetZoom-camera.zoom)*ease;camera.pivot=camera.pivot.map((x,k)=>x+(camera.targetPivot[k]-x)*ease);
 displayLayout=displayLayout.map((p,i)=>p.map((v,k)=>v+(targetLayout[i][k]-v)*ease));backdrop(width,height,now);points=displayLayout.map((p,i)=>({...project(p,width,height),i}));const neighbors=new Map();for(const e of options.edges)if(e.a!==e.b&&(e.a===options.patient||e.b===options.patient))neighbors.set(e.a===options.patient?e.b:e.a,e.similarity);
 const top=[...neighbors].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([i])=>i);
 for(const e of options.edges){if(e.a===e.b)continue;const a=points[e.a],b=points[e.b],active=options.focus&&(e.a===options.patient||e.b===options.patient),lens=options.lens&&pointer&&Math.hypot((a.x+b.x)/2-pointer.x,(a.y+b.y)/2-pointer.y)<90;
 line(a,b,active?'rgba(77,218,237,.72)':lens?'rgba(82,186,216,.6)':options.focus?'rgba(45,93,124,.14)':'rgba(61,146,176,.34)',active?1.3+e.weight:Math.max(.5,e.weight),e.source==='topk'?[4,6]:[]);
 if(active&&options.orbit){const t=(now*.00018+e.a*.173+e.b*.137)%1;ctx.beginPath();ctx.arc(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,1.7,0,Math.PI*2);ctx.fillStyle='#9df6ff';ctx.fill();}
 if((active&&top.includes(e.a===options.patient?e.b:e.a))||lens)textLabel(e.similarity.toFixed(2),(a.x+b.x)/2,(a.y+b.y)/2-5,'#80d9e9');}
 const order=[...points].sort((a,b)=>b.z-a.z);for(const point of order){const i=point.i,p=options.patients[i],active=options.focus&&i===options.patient,near=neighbors.has(i),compare=i===options.compare,fade=options.focus&&!active&&!near&&!compare,r=Math.sqrt(25+56*p.p)*(active?1.55:compare?1.3:1)*point.scale,c=color(p.p),alpha=(fade?.22:1)*(Math.max(.45,1-Math.max(0,point.z)*.16));point.r=r;
 ctx.globalAlpha=alpha;if(active){const glow=ctx.createRadialGradient(point.x,point.y,r*.4,point.x,point.y,r*3.8);glow.addColorStop(0,`rgba(${c},${active?.4:.2})`);glow.addColorStop(1,`rgba(${c},0)`);ctx.fillStyle=glow;ctx.fillRect(point.x-r*4,point.y-r*4,r*8,r*8);}
 const sphere=ctx.createRadialGradient(point.x-r*.35,point.y-r*.4,0,point.x,point.y,r);sphere.addColorStop(0,'#e6f8ff');sphere.addColorStop(.3,`rgb(${c})`);sphere.addColorStop(1,`rgb(${c.map(v=>Math.round(v*.35))})`);ctx.beginPath();ctx.arc(point.x,point.y,r,0,Math.PI*2);ctx.fillStyle=sphere;ctx.fill();
 const mc=p.mc;if(mc){const cross=mc.lo<.5&&mc.hi>.5;ctx.strokeStyle=cross?'rgba(242,201,76,.65)':'rgba(101,179,202,.4)';ctx.setLineDash(cross?[2,4]:[]);ctx.lineWidth=.8;ctx.beginPath();ctx.arc(point.x,point.y,r+4+Math.min(mc.sd/.15,1)*8,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}
 if(p.label===null){ctx.beginPath();ctx.arc(point.x,point.y,r+4,0,Math.PI*2);ctx.strokeStyle='#e8f6ff';ctx.lineWidth=1.5;ctx.stroke();}
 if(options.validation&&(p.label===0||p.label===1)){ctx.strokeStyle=p.label?'#43a5ff':'#f2994a';ctx.lineWidth=2;ctx.setLineDash(p.label?[]:[3,3]);ctx.beginPath();ctx.arc(point.x,point.y,r+3,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}
 if(active||compare||hover===i){ctx.strokeStyle=compare?'#f2c94c':'#98ecff';ctx.lineWidth=1.4;ctx.beginPath();ctx.ellipse(point.x,point.y,r+12,(r+12)*.66,motion?now*.0003:0,0,Math.PI*1.7);ctx.stroke();}
 ctx.filter='none';ctx.globalAlpha=1;if(active){textLabel(p.id,point.x,point.y-r-22,'#ecfbff');textLabel((p.p*100).toFixed(1)+'%  pCR',point.x,point.y+r+35,'#a0ddff');}else if((options.focus&&top.includes(i))||compare||hover===i)textLabel(p.id,point.x,point.y-r-11,fade?'#749ab4':'#b8d7e9');}
 paintLabels(width,height);if(options.lens&&pointer){ctx.beginPath();ctx.arc(pointer.x,pointer.y,90,0,Math.PI*2);ctx.strokeStyle='#82b9cd';ctx.lineWidth=1;ctx.stroke();}
 paintedFrames++;lastPaintMs=performance.now()-paintStart;canvas.dataset.focus=options.focus?String(options.patient):'';canvas.dataset.center=JSON.stringify(points[options.patient]);canvas.dataset.camera=JSON.stringify([camera.yaw,camera.pitch,...camera.pivot]);raf=requestAnimationFrame(tick);
}
function hit(x,y){return [...points].filter(p=>Math.hypot(p.x-x,p.y-y)<Math.max(14,(p.r||8)+4)).sort((a,b)=>a.z-b.z)[0]?.i??-1;}
function bind(){const pos=e=>{const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};};
 canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);const p=pos(e);touches.set(e.pointerId,p);drag={id:e.pointerId,x:p.x,y:p.y,startX:p.x,startY:p.y,moved:false};if(touches.size===2){const [a,b]=[...touches.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom:camera.zoom};}};
 canvas.onpointermove=e=>{dirty=true;pointer=pos(e);if(touches.has(e.pointerId))touches.set(e.pointerId,pointer);if(pinch&&touches.size===2){const [a,b]=[...touches.values()];camera.targetZoom=camera.zoom=clamp(pinch.zoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinch.distance),.55,2.2);if(drag)drag.moved=true;return;}if(drag&&drag.id===e.pointerId){if(Math.hypot(pointer.x-drag.startX,pointer.y-drag.startY)>4)drag.moved=true;if(drag.moved){camera.targetYaw+=(pointer.x-drag.x)*.007;camera.targetPitch=clamp(camera.targetPitch+(pointer.y-drag.y)*.005,-1.15,1.15);}drag.x=pointer.x;drag.y=pointer.y;return;}hover=hit(pointer.x,pointer.y);canvas.style.cursor=hover>=0?'pointer':'grab';const tip=canvas.parentElement.querySelector('.tooltip');if(tip){tip.hidden=hover<0;if(hover>=0){const p=options.patients[hover];tip.textContent=`${p.id} · pCR ${(p.p*100).toFixed(1)}%${p.mc?' · MC SD '+p.mc.sd.toFixed(3):''}${p.label===null?' · 无标签':options.validation?' · '+(p.label?'pCR':'non-pCR'):''}`;tip.style.left=clamp(pointer.x+16,8,canvas.clientWidth-240)+'px';tip.style.top=clamp(pointer.y+16,8,canvas.clientHeight-70)+'px';}}};
 canvas.onpointerup=e=>{const p=pos(e),clicked=drag&&!drag.moved&&!pinch;touches.delete(e.pointerId);drag=null;pinch=null;if(clicked){const i=hit(p.x,p.y);if(i>=0)options.onSelect(i,e.shiftKey);}};
 canvas.onpointercancel=()=>{drag=null;pinch=null;touches.clear();};canvas.onpointerleave=()=>{dirty=true;hover=-1;pointer=null;const tip=canvas.parentElement.querySelector('.tooltip');if(tip)tip.hidden=true;};
 canvas.onwheel=e=>{dirty=true;e.preventDefault();camera.targetZoom=camera.zoom=clamp(camera.zoom*Math.exp(-e.deltaY*.001),.55,2.2);};
 canvas.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key)){dirty=true;e.preventDefault();if(e.key==='ArrowLeft')camera.targetYaw-=.15;if(e.key==='ArrowRight')camera.targetYaw+=.15;if(e.key==='ArrowUp')camera.targetPitch=clamp(camera.targetPitch-.1,-1.15,1.15);if(e.key==='ArrowDown')camera.targetPitch=clamp(camera.targetPitch+.1,-1.15,1.15);if(e.key==='+')camera.targetZoom=camera.zoom=clamp(camera.zoom*1.1,.55,2.2);if(e.key==='-')camera.targetZoom=camera.zoom=clamp(camera.zoom/1.1,.55,2.2);}};
}
window.RespGraph3D={mount(element,next){next.patient=clamp(next.patient||0,0,next.patients.length-1);const key=next.patients.map(p=>p.id).join(',')+':'+next.edges.map(e=>`${e.a},${e.b},${e.weight}`).join(';');if(key!==layoutKey){selected=undefined;layout=makeLayout(next.patients.length,next.edges);layoutKey=key;displayLayout=layout.map(p=>[...p]);targetLayout=layout.map(p=>[...p]);}options=next;dirty=true;
 const focus=next.focus?next.patient:null;if(focus!==selected){selected=focus;camera.targetPivot=focus===null?[0,0,0]:[...layout[focus]];camera.targetZoom=focus===null?1:1.08;camera.targetYaw+=.75;camera.targetPitch=focus===null?-.18:-.12+Math.sin(focus*1.7)*.2;targetLayout=focusLayout(focus,next);} 
 if(canvas!==element){cancelAnimationFrame(raf);canvas=element;camera.zoom=reduced.matches?camera.targetZoom:.7;ctx=canvas.getContext('2d');hover=-1;pointer=null;drag=null;pinch=null;touches.clear();bind();previousTime=performance.now();raf=requestAnimationFrame(tick);}},stop(){cancelAnimationFrame(raf);raf=0;canvas=null;},reset(){selected=null;if(layout)targetLayout=layout.map(p=>[...p]);camera.targetZoom=1;camera.targetPivot=[0,0,0];camera.targetPitch=-.18;camera.targetYaw+=.45;},debug(){return {points:points.map(p=>({...p})),camera:{...camera},layout,selected,active:!!raf,paintedFrames,lastPaintMs};}};
})();
