/* Lazy atlas slicing + an on-demand surface renderer. No model inference or continuous animation. */
(()=>{'use strict';const manifest=window.RESPGRAPH_MRI,imageCache=new Map(),meshes=new Map(),pending=new Map();let current=null;
function image(src){if(imageCache.has(src))return imageCache.get(src);const promise=new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('影像资源未能载入'));img.src=src;});imageCache.set(src,promise);while(imageCache.size>4)imageCache.delete(imageCache.keys().next().value);promise.catch(()=>imageCache.delete(src));return promise;}
function loadMesh(id){if(meshes.has(id))return Promise.resolve(meshes.get(id));if(pending.has(id))return pending.get(id).promise;let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});pending.set(id,{promise,resolve,reject});const script=document.createElement('script');script.src=manifest.patients[id].mesh;script.onload=()=>script.remove();script.onerror=()=>{pending.delete(id);script.remove();reject(Error('三维形态资源未能载入'));};document.head.append(script);return promise;}
function registerMesh(id,data){const normals=data.vertices.map(()=>[0,0,0]);for(const f of data.faces){const a=data.vertices[f[0]],b=data.vertices[f[1]],c=data.vertices[f[2]],u=b.map((v,k)=>v-a[k]),v=c.map((x,k)=>x-a[k]),n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];for(const i of f)for(let k=0;k<3;k++)normals[i][k]+=n[k];}data.normals=normals.map(n=>{const length=Math.hypot(...n)||1;return n.map(v=>v/length);});meshes.set(id,data);if(pending.has(id)){pending.get(id).resolve(data);pending.delete(id);}}
function html(id,comparison=null){if(!manifest?.patients[id])return '';return `<section class="panel imaging-panel" id="patient-imaging" aria-label="患者真实MRI与分割形态"><div class="split-head"><div><div class="eyebrow">SOURCE MRI / SEGMENTATION</div><h2>真实MRI与肿瘤轮廓</h2><p class="small">首次访视影像 · 切换采集序列、浏览切片，查看分割区域的三维形态。</p></div><span class="badge">与患者编号联动</span></div><div class="imaging-toolbar"><span>查看</span><button data-mri-patient="${id}" aria-pressed="true">${id}</button>${comparison?`<button data-mri-patient="${comparison}" aria-pressed="false">${comparison}</button>`:''}<label>采集序列 <select id="mri-acquisition" aria-label="MRI采集序列"></select></label><label><input id="mri-overlay" type="checkbox" checked> 分割轮廓</label></div><div class="imaging-grid"><div class="mri-slice-wrap"><canvas id="mri-slice" role="img" aria-label="真实MRI切片与mask叠加"></canvas><div class="mri-canvas-label" id="mri-image-label"></div><div class="mri-slice-controls"><button id="mri-prev" aria-label="上一张切片">−</button><input id="mri-slice-range" type="range" aria-label="MRI切片编号"><button id="mri-next" aria-label="下一张切片">＋</button><output id="mri-slice-number"></output></div><button class="quiet" id="mri-lesion">定位分割区域最大的切片</button></div><div class="mri-surface-wrap"><canvas id="mri-surface" tabindex="0" role="img" aria-label="肿瘤分割区域的三维形态，拖动或方向键旋转，滚轮缩放"></canvas><div class="mri-canvas-label">分割区域 · 三维重建</div><div class="mri-mesh-controls"><span>拖动旋转 · 滚轮缩放</span><button id="mri-reset">复位</button><label><input id="mri-wire" type="checkbox"> 网格</label></div></div></div><div class="mri-status" id="mri-status" role="status"></div><div class="imaging-caption"><span><i></i>青色轮廓：已有mask标注</span><span>vis1首次访视；采集序列属于同次检查。</span></div></section>`;}
function mount(id,comparison=null){const host=document.getElementById('patient-imaging');if(!host||current?.host===host)return;if(current)current.destroy();
 const $=s=>host.querySelector(s),slice=$('#mri-slice'),surface=$('#mri-surface'),ctx=slice.getContext('2d'),mc=surface.getContext('2d');let alive=true,request=0,entry,phase,volume,mask,mesh,yaw=-.6,pitch=.4,zoom=1,drag=null,sliceFrame=0,meshFrame=0;const state={host,id,destroy(){alive=false;request++;observer.disconnect();cancelAnimationFrame(sliceFrame);cancelAnimationFrame(meshFrame);}};current=state;
 function size(canvas){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);return [canvas.width,canvas.height];}
 function drawSlice(){if(!alive||!volume||!mask)return;const [w,h]=size(slice),z=Number($('#mri-slice-range').value),sx=z%entry.columns*entry.tile_width,sy=Math.floor(z/entry.columns)*entry.tile_height;ctx.fillStyle='#040b12';ctx.fillRect(0,0,w,h);const k=Math.min(w/entry.tile_width,h/entry.tile_height),dw=entry.tile_width*k,dh=entry.tile_height*k,x=(w-dw)/2,y=(h-dh)/2;ctx.drawImage(volume,sx,sy,entry.tile_width,entry.tile_height,x,y,dw,dh);if($('#mri-overlay').checked)ctx.drawImage(mask,sx,sy,entry.tile_width,entry.tile_height,x,y,dw,dh);$('#mri-slice-number').textContent=(z+1)+' / '+entry.slice_count;$('#mri-image-label').textContent=state.id+' · 采集 '+phase;}
 function drawMesh(){if(!alive||!mesh)return;const [w,h]=size(surface);mc.fillStyle='#06121e';mc.fillRect(0,0,w,h);const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),unit=Math.min(w,h)*.34*zoom;const points=mesh.vertices.map(v=>{const x=v[1]*cy+v[2]*sy,z=-v[1]*sy+v[2]*cy,y=v[0]*cp-z*sp,depth=v[0]*sp+z*cp,k=4/(4+depth*.35);return [w/2+x*unit*k,h/2+y*unit*k,depth];});
 const lighting=mesh.normals.map(n=>{const x=n[1]*cy+n[2]*sy,z=-n[1]*sy+n[2]*cy,y=n[0]*cp-z*sp,depth=n[0]*sp+z*cp;return .3+.7*Math.abs(x*.2-y*.5+depth*.8);});const triangles=mesh.faces.map(f=>{const a=points[f[0]],b=points[f[1]],c=points[f[2]],shade=(lighting[f[0]]+lighting[f[1]]+lighting[f[2]])/3;return {a,b,c,z:(a[2]+b[2]+c[2])/3,shade};}).sort((a,b)=>b.z-a.z);
 for(const t of triangles){mc.beginPath();mc.moveTo(t.a[0],t.a[1]);mc.lineTo(t.b[0],t.b[1]);mc.lineTo(t.c[0],t.c[1]);mc.closePath();mc.fillStyle=`rgb(${Math.round(45+60*t.shade)},${Math.round(86+134*t.shade)},${Math.round(110+124*t.shade)})`;mc.fill();if($('#mri-wire').checked){mc.strokeStyle='#b3efff44';mc.lineWidth=.45;mc.stroke();}}
 surface.dataset.patient=state.id;surface.dataset.triangles=mesh.faces.length;surface.dataset.camera=JSON.stringify([yaw,pitch,zoom]);}
 function scheduleSlice(){cancelAnimationFrame(sliceFrame);sliceFrame=requestAnimationFrame(drawSlice);}function scheduleMesh(){cancelAnimationFrame(meshFrame);meshFrame=requestAnimationFrame(drawMesh);}
 async function acquisition(){const token=++request;$('#mri-status').textContent='正在载入 '+state.id+' 的MRI…';const targetPhase=Number($('#mri-acquisition').value);try{const [a,b]=await Promise.all([image(entry.acquisitions.find(p=>p.index===targetPhase).atlas),image(entry.mask)]);if(!alive||token!==request)return;phase=targetPhase;volume=a;mask=b;drawSlice();$('#mri-status').textContent='';}catch(e){if(alive&&token===request)$('#mri-status').textContent=e.message;}}
 async function select(next){state.id=next;entry=manifest.patients[next];volume=mask=mesh=null;for(const c of [ctx,mc]){c.clearRect(0,0,c.canvas.width,c.canvas.height);}$('#mri-acquisition').innerHTML=entry.acquisitions.map(a=>`<option value="${a.index}">采集 ${a.index}</option>`).join('');$('#mri-acquisition').value=String(entry.acquisitions[Math.min(2,entry.acquisitions.length-1)].index);$('#mri-slice-range').min=0;$('#mri-slice-range').max=entry.slice_count-1;$('#mri-slice-range').value=entry.representative_slice;host.querySelectorAll('[data-mri-patient]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mriPatient===next));yaw=-.6;pitch=.4;zoom=1;const expected=next;acquisition();try{const m=await loadMesh(next);if(!alive||state.id!==expected)return;mesh=m;drawMesh();}catch(e){if(alive&&state.id===expected)$('#mri-status').textContent=e.message;}}
 $('#mri-acquisition').onchange=acquisition;$('#mri-slice-range').oninput=scheduleSlice;$('#mri-overlay').onchange=scheduleSlice;$('#mri-wire').onchange=scheduleMesh;$('#mri-prev').onclick=()=>{$('#mri-slice-range').value=Math.max(0,Number($('#mri-slice-range').value)-1);scheduleSlice();};$('#mri-next').onclick=()=>{$('#mri-slice-range').value=Math.min(entry.slice_count-1,Number($('#mri-slice-range').value)+1);scheduleSlice();};$('#mri-lesion').onclick=()=>{$('#mri-slice-range').value=entry.representative_slice;scheduleSlice();};$('#mri-reset').onclick=()=>{yaw=-.6;pitch=.4;zoom=1;scheduleMesh();};host.querySelectorAll('[data-mri-patient]').forEach(b=>b.onclick=()=>select(b.dataset.mriPatient));
 surface.onpointerdown=e=>{drag=[e.clientX,e.clientY];surface.setPointerCapture(e.pointerId);};surface.onpointermove=e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.01;pitch+=(e.clientY-drag[1])*.01;drag=[e.clientX,e.clientY];scheduleMesh();};surface.onpointerup=surface.onpointercancel=()=>drag=null;surface.onwheel=e=>{e.preventDefault();zoom=Math.max(.5,Math.min(2,zoom*Math.exp(-e.deltaY*.001)));scheduleMesh();};surface.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();yaw+=e.key==='ArrowLeft'?-.15:e.key==='ArrowRight'?.15:0;pitch+=e.key==='ArrowUp'?-.15:e.key==='ArrowDown'?.15:0;scheduleMesh();}};
 const observer=new ResizeObserver(()=>{scheduleSlice();scheduleMesh();});observer.observe(slice);observer.observe(surface);select(id);}
 function stop(){if(current)current.destroy();current=null;}
 window.RespMRI={html,mount,stop,registerMesh};})();
