/* Organize existing views without changing model outputs or dataset values. */
(()=>{'use strict';let settingsOpen=false;
function background(root){const console=root.querySelector('.background-console'),cols=[...console.children],timeline=root.querySelector('.clinical-timeline').closest('section'),heat=root.querySelector('.cohort-map-panel'),photo=root.querySelector('.clinical-mri-preview');
 const more=document.createElement('details');more.className='cohort-more';more.innerHTML='<summary>浏览38位患者的肿瘤体积变化</summary>';more.append(heat);console.after(more);cols[1].append(timeline);timeline.classList.add('journey-panel');timeline.querySelector('h2').textContent='治疗中观察变化，手术后核对结果';if(photo)timeline.querySelector('.clinical-timeline').before(photo);
 const question=document.createElement('section');question.className='panel clinical-question';question.innerHTML='<h2>治疗过程中，怎样提前评估疗效？</h2><p>用MRI记录患者的变化，预测达到病理完全缓解的可能性，再解释模型判断的依据。</p><div class="journey-prediction"><span>治疗期间</span><strong>预测pCR概率</strong><span>手术之后</span><strong>核对病理结果</strong></div>';cols[0].prepend(question);}
function evidence(root){const toolbar=root.querySelector('.toolbar'),old=root.querySelector('.grid2'),sections=[...old.children],cm=root.querySelector('.confusion').closest('section'),metrics=root.querySelector('.metrics'),primary=document.createElement('div'),secondary=document.createElement('div');primary.className='evidence-primary';secondary.className='grid2 evidence-secondary';primary.append(sections[0],sections[1],cm);secondary.append(sections[3],sections[2]);metrics.after(primary);const structure=root.querySelector('.structure-review');structure.classList.add('compact-structure');structure.querySelector('.finding-note')?.remove();primary.after(structure);structure.after(secondary);old.remove();const ranked=root.querySelector('[data-ranked-patient]')?.closest('section');if(ranked)secondary.after(ranked);sections[1].querySelector('h2').textContent='外部验证 · ROC';}
function sandbox(root){const editor=root.querySelector('.cohort-editor'),bar=editor.nextElementSibling,details=document.createElement('details');details.className='cohort-settings';details.innerHTML='<summary>编辑患者队列与新增病例</summary>';details.open=settingsOpen;editor.before(details);details.append(editor,bar);details.ontoggle=()=>settingsOpen=details.open;
 root.querySelectorAll('[data-feature]').forEach(input=>{input.dataset.precise=input.value;const shorten=()=>{if(input.dataset.precise.trim()&&Number.isFinite(Number(input.dataset.precise)))input.value=String(Number(Number(input.dataset.precise).toFixed(4)));};shorten();input.onfocus=()=>input.value=input.dataset.precise;input.oninput=()=>input.dataset.precise=input.value;input.onblur=shorten;});}
function enhance(S){const root=document.getElementById('content');if(S.page==='background')background(root);if(S.page==='evidence')evidence(root);if(S.page==='sandbox')sandbox(root);}
window.RespRefinement={enhance};})();
