/* Desktop presentation panels; mobile retains natural document flow. */
(()=>{'use strict';const saved={};let redraw;const $=(r,s)=>r.querySelector(s);function mount(state,draw){redraw=draw;const root=document.getElementById('content');document.body.dataset.page=state.page;const groups=[];const add=(name,nodes,kind='')=>{nodes=nodes.filter(Boolean);if(nodes.length)groups.push({name,nodes,kind});};
switch(state.page){
case 'background':{const map=$(root,'.cohort-response-map');if(map){const header=map.firstElementChild,rows=[...map.querySelectorAll('button')];for(let part=0;part<2;part++){const half=document.createElement('div');half.className='response-half';half.append(header.cloneNode(true));rows.slice(part*19,(part+1)*19).forEach(n=>half.append(n));map.append(half);}header.remove();}}add('治疗与检查',[$(root,'.background-console')],'clinical');add('政策与数据来源',[$(root,'.clinical-policy'),$(root,'.overview-sources')],'sources');break;
case 'story':add('患者关系与解释',[$(root,'.research-console')],'overview');add('验证结果',[$(root,'.console-bottom'),$(root,'.clinical-use')],'verification');break;
case 'graph':add('患者关系空间',[$(root,'.graph-grid'),$(root,'.comparison-bar')],'spatial');add('病例入口与图例',[$(root,'.discovery-strip'),$(root,'.encoding-guide')],'cases');break;
case 'patient':{const extra=$(root,'.sensitivity-details');if(extra)extra.open=true;}add('检查与双人比较',[$(root,'.patient-layout')],'trajectories');add('SHAP与注意力',[$(root,'.explain-section')],'explanation');add('输入扰动分析',[$(root,'.sensitivity-details')],'sensitivity');break;
case 'evidence':{const grid=$(root,'.grid2'),cards=grid?[...grid.children]:[],metric=$(root,'.metrics');add('关系结构与ROC',[metric,...cards.slice(0,2)],'experiment');add('结局与概率',[cards[2],...root.querySelectorAll(':scope > .panel')].filter(n=>n?.querySelector('.confusion')),'outcomes');if(cards[2]&&!groups[groups.length-1]?.nodes.includes(cards[2]))groups[groups.length-1]?.nodes.unshift(cards[2]);add('队列组成与稳定性',[cards[3],$(root,'.stability-section')],'stability');add('结构对照与逐患者结果',[$(root,'.structure-review'),$(root,'.ranked-section')],'ranked');if(grid)grid.remove();break;}
case 'sandbox':add('队列关系与结果',[$(root,'.comparison-bar'),$(root,'#cohort-output')],'cohort');add('增删患者',[$(root,'.cohort-editor')],'editor');break;
case 'boundary':add('模型与队列',[$(root,'.story-flow'),$(root,'.grid2')],'methods');add('实验记录与下载',[...root.querySelectorAll(':scope > .panel')],'records');break;
}if(!groups.length)return;const nav=document.createElement('nav');nav.className='stage-tabs';nav.setAttribute('aria-label','当前页面内容');const holder=document.createElement('div');holder.className='stage-holder';groups.forEach((g,i)=>{const pane=document.createElement('section');pane.className='stage-pane stage-'+g.kind;pane.dataset.stage=String(i);g.nodes.forEach(n=>pane.append(n));holder.append(pane);const b=document.createElement('button');b.textContent=g.name;b.dataset.stageTab=String(i);b.onclick=()=>activate(i);nav.append(b);});root.append(nav,holder);function activate(i){saved[state.page]=i;nav.querySelectorAll('button').forEach((b,j)=>b.setAttribute('aria-pressed',String(j===i)));holder.querySelectorAll('.stage-pane').forEach((p,j)=>p.hidden=j!==i);requestAnimationFrame(()=>redraw());}activate(Math.min(saved[state.page]||0,groups.length-1));
}
function reveal(target){const n=document.querySelector(target),pane=n?.closest('.stage-pane');if(pane){const b=document.querySelector(`[data-stage-tab="${pane.dataset.stage}"]`);b?.click();}return n;}
window.RespStage={mount,reveal};})();
